### ISSUE TITLE
New version of Swiftgger built with swift 5.2

### ISSUE THREAD

**Issue by AndriyVasyk** [mczachurski/Swiftgger#23]
Hello!
Could you please to release separate version of Swiftgger built with swift 5.2?
We are using Vapor 4.0 and Docker. And the problem is we need to use swift 5.2 according the the following document:
https://docs.vapor.codes/4.0/deploy/docker/

**Comment by mczachurski** [comment]
Hi, it would be difficult because we are using `Resources` feature in SPM which is available since Swift 5.3.

I'm not sure that you should use that Docker image. It seems that Vapor team deprecated that Docker image: https://github.com/vapor/docker.

It's much better to use separate docker image with clean Ubuntu LTS 20.04, you have also official Swift support for that OS version. Or you can use official Swift image: https://hub.docker.com/_/swift (you don't have to install Vapor for build/run your code in Docker).

**Comment by AndriyVasyk** [comment]
Thank you for responding. You are right. We really need to use separate docker image.
